TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

# Create and install (or just install)
# databases, templates, substitutions like this
DB += ISEG_EHS_channel.db
DB += ISEG_EHS_module.db
DB += LEDPulser.db
DB += THMP_COM.db
DB += THMP_other.db
DB += THMP_temp.db
DB += tmcm.db
DB += WienerVMEcrate.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

